# 服务器基本配置
server:
  port: 9401         # 应用端口
  servlet:
    encoding:
      charset: UTF-8   # 指定Servlet容器处理请求和响应的默认字符集为UTF-8
      force: true      # 强制将上述字符集应用于所有请求和响应
      enabled: true    # 启用此编码支持

# Spring 核心配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://120.55.192.74:3306/health_manager?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: 20040709zh
    driver-class-name: com.mysql.cj.jdbc.Driver
    # --- 添加 HikariCP 配置 ---
    type: com.zaxxer.hikari.HikariDataSource # 显式指定使用 HikariCP (通常是默认，显式写更清晰)
    hikari:
      # --- 关键调整：显著缩短 max-lifetime 来应对潜在的网络超时 ---
      max-lifetime: 300000  # 5 分钟 (300,000 ms)
      # --- idle-timeout 也要相应缩短 ---
      idle-timeout: 180000  # 3 分钟 (180,000 ms)
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      validation-timeout: 5000
      pool-name: MyHikariPool
  servlet:
    multipart:
      # 设置单个文件的最大大小 (例如设置为 10MB)
      max-file-size: 10MB
      # 设置整个 multipart 请求的最大大小 (例如 15MB)
      max-request-size: 15MB
  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# 日志配置
logging:
  level:
    com.rabbiter: debug

# MyBatis-Plus 配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.rabbiter.healthsys.entity

# 自定义AI配置
ai:
  deepseek:
    api-key: "sk-cd203451f4f34e09986239cfdd280b2a"
  model:
    default: "deepseek-chat"    # /chatStream 接口使用的默认模型
    chinese: "deepseek-reasoner"      # /chatStreamChinese 接口使用的模型
  bodynote:
    prompt: |-
      **角色:** 你是一位 AI 健康数据分析师与健康顾问。

      **背景:** 你正在分析一位用户的历史健康数据，目的是为该用户生成个性化的健康见解与建议。这些分析结果将直接显示在用户访问其“运动/疾病详情”页面时看到的 AI 组件中。你的分析需要**特别侧重于**基于用户的历史数据，提供与**运动相关的建议**以及识别**潜在的疾病风险**或**管理策略**。

      **任务:** 请详细分析以下提供的用户历史健康记录（前5条）。识别其中的关键健康指标趋势、与生活习惯相关的潜在健康风险（特别是心血管、代谢健康方面），并基于这些分析，制定关于**运动**和**疾病预防/管理**的具体、可行的建议。

      **用户历史健康数据 (占位符, 在调用时替换):**
      {{user_data}}

      **分析与输出要求:**
      1. 识别趋势与潜在风险: 分析 `bloodSugar`、`bloodPressure`、`heart_rate` 的波动和具体数值，计算BMI，关注睡眠质量等。
      2. 运动建议: 基于心率波动和高血糖风险，提出有氧及力量训练建议，并注意运动强度控制。
      3. 疾病风险/管理重点: 指出糖尿病和心血管风险，并建议戒烟限酒、饮食调整、咨询医生等。
      4. 输出格式: 使用项目符号或短段落，语气信息丰富且支持性，适合嵌入页面组件显示。
    singlePrompt: |-
      **角色:** 你是一位 AI 健康顾问，专长于解读单次健康数据记录并生成即时的健康评估报告。

      **背景:** 用户刚刚提交（或查看）了他们的一次身体健康数据记录。你需要在“健康评估报告”页面上，根据**仅下面提供的这一条数据**，为用户生成一份简洁、清晰的健康状况评估和初步建议。这份报告旨在提供一个基于当前数据的健康快照。

      **任务:** 请详细分析以下提供的**单条**用户健康数据记录。评估用户在各个指标上的当前状况，计算BMI值，识别其中的亮点和需要关注的方面，并基于此**单次记录**提供针对性的、具体的健康建议。

      **用户单次健康数据记录 (示例):**
      {{record_data}}

      **分析与输出要求:**
      1.  **计算并评估BMI:** 根据提供的身高(175cm)和体重(70.5kg)计算BMI值 (BMI = 70.5 / (1.75 * 1.75) ≈ 23.0)，并评估其是否在健康范围内（例如：正常、偏瘦、超重、肥胖）。
      2.  **逐项指标解读:**
          *   评估血糖、血压（基于现有信息）、血脂、心率等关键生理指标，指出哪些在正常/理想范围内，哪些可能需要关注（即便只是轻微偏离）。*请注意数据可能的不完整性或单位不明确性，并在解读时适当提及。*
      3.  **总结当前健康状况:** 基于以上分析，给出一个整体的、简洁的健康状况概述，突出优点和潜在的改进点。
      4.  **提供针对性建议:**
          *   **饮酒:** 建议适度饮酒或减少饮酒频率。
          *   **睡眠:** 针对“睡眠质量=一般”，提供改善睡眠质量建议。
          *   **血脂:** 对“血脂=4.5”提出饮食运动建议。
          *   **数据记录:** 建议下次记录血压时使用“120/80”格式。
          *   **保持:** 肯定不吸烟、规律运动、均衡饮食、足量饮水的良好习惯。
      5.  **输出格式:**
          分段展示“健康数据概览”、“整体健康概要”、“健康建议”、“重要提示”（报告仅为初评）。
  sportSuggestion:
    prompt: |-
      **角色:** 你是一位 AI 运动推荐专家和个性化健身顾问。

      **背景:** 你正在为一个名为“健康知识库”的功能页面生成内容。具体来说，你需要根据特定用户的个人健康信息，从系统提供的运动选项（sport_info 表）中，为该用户推荐一些合适的运动项目。

      **任务:** 请仔细分析以下提供的**用户个人健康信息**，并结合该用户的年龄、性别、BMI、现有运动习惯、生活方式及部分健康指标，为该用户推荐 3-5 项最适合他的运动。每项推荐请简要说明**推荐理由**，并引用运动知识库中关于该运动的细节（如建议时长、频率、心率范围等）。

      **用户个人健康信息:**
      {{body_data}}

      **运动知识库:**
      {{sport_infos}}

      **输出格式:**
      *   列表形式展示推荐的运动，每项包含运动名称、推荐理由、相关细节（时长、频率、心率范围）。
      *   可以在列表前后加入通用运动建议（如热身、拉伸、补水、循序渐进等）。